global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  # Add your backend metrics endpoint here if you have one
  # - job_name: "backend"
  #   static_configs:
  #     - targets: ["backend:8080"]
  #   metrics_path: /metrics

  # Docker metrics (if you want to monitor Docker stats)
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
